services:
  db:
    image: postgres:latest
    container_name: sehenos_db
    environment:
      POSTGRES_DB: sehenos_db
      POSTGRES_USER: sehenos
      POSTGRES_PASSWORD: piswos
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sehenos_network

  app:
    build: ./backend
    container_name: sehenos_app
    environment:
      - FLASK_ENV=development
    networks:
      - sehenos_network
    # ports:
    #   - "5000:5000"
    # depends_on:
    #   - db

  web:
    build: ./frontend
    container_name: sehenos_web
    networks:
      - sehenos_network
    # ports:
    #   - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: sehenos_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - app
    networks:
      - sehenos_network

networks:
  sehenos_network:
    drive: bridge

volumes:
  postgres_data:
