# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: sehenos-db
    environment:
      - POSTGRES_DB=sehenos-db
      - POSTGRES_USER=cypher
      - POSTGRES_PASSWORD=piswos
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - sehenos
  
  redis:
    image: redis:alpine
    container_name: sehenos-redis
    ports:
      - "6379:6379"
    networks:
      - sehenos

  app:
    build: ./backend
    container_name: sehenos-app
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - sehenos

  web:
    build: ./frontend
    container_name: sehenos-web
    networks:
      - sehenos

  nginx:
    image: nginx:1.27.1-alpine-slim
    container_name: sehenos-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.d
    depends_on:
      - web
      - app
    networks:
      - sehenos

networks:
  sehenos:
    name: sehenos

volumes:
  postgresql:
