version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sehenos
      POSTGRES_PASSWORD: piswos
      POSTGRES_DB: sehenos_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sehenos_network

  api:
    build: ./backend
    depends_on:
      - db
    networks:
      - sehenos_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - sehenos_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
    networks:
      - sehenos_network

networks:
  sehenos_network:

volumes:
  db_data:
